# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main", "fish3.4" ]
  pull_request:
    branches: [ "main", "fish3.4" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  fish-3.4.0:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install fish  # mostly copied from fish-shell's own actions
      env:
        CXXFLAGS: "-Werror=address -Werror=return-type"
      run: |
        sudo apt install gettext libncurses5-dev libpcre2-dev python3-pip tmux
        sudo pip3 install pexpect
        # Generate a locale that uses a comma as decimal separator.
        # sudo locale-gen fr_FR.UTF-8
        git clone https://github.com/fish-shell/fish-shell.git --single-branch --branch 3.4.0 --depth 1
        cd fish-shell
        mkdir build && cd build
        cmake ..
        make
        # make test
        pwd | tee -a "${GITHUB_PATH}"

    - name: Install dependencies
      run: |
        sudo apt install tmux inotify-tools perl

    - name: Run tests
      run: |
        ./run-tests
